[package]
name = "career"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "career.rs"

[dependencies]
async-openai.workspace = true
anyhow.workspace = true
log.workspace = true
pdf-extract.workspace = true

[lints]
workspace = true
